name: .NET Ensure Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild.exe path
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Restore NuGet packages
      run: nuget restore SemanticXamlPrint/SemanticXamlPrint.csproj

    - name: Build
      run: msbuild SemanticXamlPrint/SemanticXamlPrint.csproj /p:Configuration=Release
